theme: jekyll-theme-minimal
exclude: ["ReadMe.md"]

title : Adithya Chari
description: A personal webpage for Adithya Chari
logo: assets/profilepic.jpg
show_downloads: true
author : 
  name : Adithya Chari
  email : adithya.chari@gmail.com
  github : adchari
