theme: jekyll-theme-minimal
exclude: ["ReadMe.md"]

title : Adithya Chari
logo: assets/profilepic.jpg
show_downloads: false
author : 
  name : Adithya Chari
  email : adithya.chari@gmail.com
  github : adchari
